language: node_js
node_js:
  - "6"
dist: trusty
sudo: required

branches:
  only:
  - writing

install:
  - source travis_env_init.sh

script:
  - hexo clean
  - hexo generate
  - gulp

after_success:
  - hexo deploy > /dev/null

notifications:
  email: true
