language: node_js
node_js:
  - "6"
dist: trusty
sudo: required

branches:
  only:
  - writing

install:
- ls -al
- source travis_env_init.sh

script:
- hexo clean
- hexo generate

after_success:
- hexo deploy

notifications:
    email: true
