language: node_js
dist: trusty
sudo: required

branches:
  only:
  - writing

before_install:
- sudo npm install -g hexo
- sudo npm install -g hexo-cli
- sudo npm install -g hexo-generator-json-content
- sudo npm install -g hexo-generator-sitemap
- sudo npm install -g hexo-generator-baidu-sitemap
- sudo npm install -g hexo-generator-feed

install:
- sudo npm install

before_script:
- git config --global user.name 'zthxxx'
- git config --global user.email 'zth_9451@qq.com'
- echo ${REPO_TOKEN}
- sed -i'' "s~git@github.com:zthxxx/zthxxx.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/zthxxx/zthxxx.github.io.git~" _config.yml
- cp themes/icarus/_config.yml.example themes/icarus/_config.yml

# - hexo init test_blog
# - cd test_blog

script:
- hexo clean
- hexo generate

after_success:
- hexo deploy