language: node_js
node_js:
  - "6"
dist: trusty
sudo: required

branches:
  only:
  - writing

before_install:
- npm install -g hexo
- npm install -g hexo-cli

install:
- npm install

before_script:
- git_user_name="zthxxx"
- git_user_email="zth_9451@qq.com"
- git_post_repertory="zthxxx.github.io"
- git config --global user.name "${git_user_name}"
- git config --global user.email "${git_user_email}"
- sed -i'' "s~git@github.com:${git_user_name}/${git_post_repertory}.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/${git_user_name}/${git_post_repertory}.git~" _config.yml
- cp themes/icarus/_config.yml.example themes/icarus/_config.yml

script:
- hexo clean
- hexo generate

after_success:
- hexo deploy
